splitter/lib/splitter_web/router.ex
defmodule SplitterWeb.Router do
  use SplitterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SplitterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SplitterWeb do
    pipe_through :browser

    get "/", BillsController, :index
    post "/bills", BillsController, :create
    post "/users", BillsController, :createUser
    get "/split", BillsController, :splitBills
    delete "/bills/delete/:id", BillsController, :trash_button
    delete "/users/delete/:id", BillsController, :trashUser_button

    #get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SplitterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SplitterWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

splitter/lib/splitter/bills.ex
defmodule Splitter.Bills do
  alias Splitter.Bills.Bill
  alias Splitter.Repo
  import Ecto.Query

  def get_bill(id) do
    Repo.get(Bill, id)
  end

  def list_bills(conn) do

  end

#  def list_bills() do
#    query = Bill |> order_by(desc: :id)
#    Repo.all(query)
#  end

  def delete_bill(id) do
    bill = Repo.get(Bill, id)
    Repo.delete(bill)
  end

  def create_bill(params) do
    %Bill{}
    |> Bill.changeset(params)
  end
end

splitter/lib/splitter/bills/bill.ex
defmodule Splitter.Bills.Bill do

  use Ecto.Schema
  import Ecto.Changeset

  schema "bills" do
    field :title, :string
    field :users, :string
    field :price, :float

    timestamps()
  end

  def changeset(bill, params) do
    bill
    |> cast(params, [:title, :users, :price])
  end
end

splitter/lib/splitter_web/controllers/bills_controller.ex
defmodule SplitterWeb.BillsController do
  use SplitterWeb, :controller

  use Phoenix.LiveView
  require Logger
  use GenServer
  alias Splitter.Bills
  alias Splitter.Bills.Bill
  import Plug.Conn
  import HTTPoison
  import Ecto.Query
  import Kernel

  def index(conn, _params) do

    bills = getBillsForIndex(conn)

    users = getUsersForIndex(conn)
    changeset = Bill.changeset(%Bill{}, %{})



    render(conn, "index.html", bills: bills, users: users, changeset: changeset)
  end

  def start_link do
    HTTPoison.start_link()
  end

  def getBillsForIndex(conn) do
        bills = get_session(conn, "bills")
          case bills do
              nil ->
                  nil
                  _->
                    getBills(conn)
                    end
        end

  def getUsersForIndex(conn) do
    users = get_session(conn, "users")
    case users do
      nil ->
        nil
      _->
        getUsers(conn)
    end
  end



  def trashUser_button(conn, %{"id" => id}) do


    bills = getBills(conn)

    value_exists = case bills do
      nil -> false
      _ ->  Enum.any?(bills, fn bill -> Enum.any?(Enum.at(bill,2), fn users ->  users == {id, "true"} end) end)  ||  Enum.any?(bills, fn bill -> Enum.at(bill,4)== id end)

    end

    case value_exists do
      true ->
        conn = Phoenix.Controller.put_flash(conn, :alert, "Nie można usunąć osoby " <> id <> ", ponieważ istnieje rachunek powiązany!")
        Phoenix.Controller.redirect(conn, to: "/")
      _ ->
        users = getUsersForIndex(conn)

        selectedObj = Enum.find_index(users, fn user -> to_string(user) == to_string(id) end)

        newList = case selectedObj do
          nil ->
            users
          _ ->
            List.delete_at(users, selectedObj)
        end
        newList = case length(newList) do
          0 -> nil
          _-> newList
        end
        binary = :erlang.term_to_binary(newList)



        conn = put_session(conn, "users", binary)

        Phoenix.Controller.redirect(conn, to: "/")

    end


  end

  def trash_button(conn, %{"id" => id}) do

    bills = getBillsForIndex(conn)

    changeset = Bill.changeset(%Bill{}, %{})

    selectedObj = Enum.find_index(bills, fn bill -> to_string(Enum.at(bill,3)) == to_string(id) end)

    newList = case selectedObj do
      nil ->
        bills
      _ ->
        List.delete_at(bills, selectedObj)
    end
    newList = case length(newList) do
      0 -> nil
      _-> newList
    end

    binary = :erlang.term_to_binary(newList)
    conn = put_session(conn, "bills", binary)

    Phoenix.Controller.redirect(conn, to: "/")
  end

  def getBills(conn) do

    bills = get_session(conn, "bills")
    case bills do
      nil ->
        nil;
      _ ->
        parts = :erlang.binary_to_term(bills)
        parts
    end
    end

  def getUsers(conn) do

    users = get_session(conn, "users")
    case users do
      nil ->
        nil;
      _ ->
        parts = :erlang.binary_to_term(users)
        parts
    end
  end

  def string_to_num(string) do
    try do
      String.to_integer(string)
    rescue
      ArgumentError -> String.to_float(string)
    end
  end


  def createUser(conn, %{"bill" => user_params}) do
    user = user_params["user"]

    users = getUsers(conn)

    newList = case users do
      nil->[user];
      _->users ++ [user]
    end

    binary = :erlang.term_to_binary(newList)
    conn = put_session(conn, "users", binary)

    Phoenix.Controller.redirect(conn, to: "/")
  end



    def calcArrayBills(-1,_,_,array) do array end

    def calcArrayBills(n, bills,users,array) do
      bill = Enum.at(bills,n)
    payer = Enum.at(bill,4)
    payerIndex = Enum.find_index(users, fn user -> to_string(user) == to_string(payer) end)
    value = Enum.at(bill,1)
    countUsers= Enum.count(Enum.at(bill,2), &(elem(&1, 1) == "true"))
    splitValue= string_to_num(value)/countUsers
    newArray = calcArrayUsers(length(Enum.at(bill,2))-1, Enum.at(bill,2), users, payerIndex,splitValue, array)
    calcArrayBills(n-1, bills,users,newArray)
  end

    def calcArrayUsers(-1, _,_,_,_,array) do array end

    def calcArrayUsers(n, bill, users, payerIndex,splitValue, array) do
        billUser =  Enum.at(bill,n)

        if elem(billUser, 1) == "true" do
          index = Enum.find_index(users, fn user -> to_string(user) == to_string(elem(billUser, 0)) end)
          new_array =  List.replace_at(array, payerIndex, List.replace_at(Enum.at(array,payerIndex), index,  Enum.at(Enum.at(array,payerIndex),index) + splitValue))
          calcArrayUsers(n-1, bill, users, payerIndex, splitValue, new_array)
          else
        calcArrayUsers(n-1, bill, users, payerIndex, splitValue, array)
      end
  end

  def do_request(server, request, port) do
    case :gen_tcp.connect(server, port, [:binary, active: false]) do
      {:ok, socket} ->
        :ok = :gen_tcp.send(socket, request)
        response = :gen_tcp.recv(socket, 0)
        :gen_tcp.close(socket)
        response
      {:error, reason} ->
        {:error, reason}
    end
  end

  def splitBills(conn, params) do

    request = createArray(conn)
    port=5700
    server = {127, 0, 0, 1}
    response = do_request(server, request, port)

    array_string = elem(response,1)

    array_list = String.replace(array_string, "]]", "")
    array_list = String.replace(array_list, "[[", "")
    array_list = String.split(array_list, "],[", include_delimiter: false)

    array = Enum.map(array_list, fn x -> String.split(x, ",") end)

    users = getUsers(conn)

    users = if length(users) < 3 do
      ["temp" | users]
    else
      users
    end

    result = arrayPaymentsCheck(array, length(array)-1, users, [])

    conn = Phoenix.Controller.put_flash(conn, :splitResult,  result)
    Phoenix.Controller.redirect(conn, to: "/")
  end

  def arrayPaymentsCheck(_, -1, _, result) do result end

  def arrayPaymentsCheck(array, rowIndex, users, result) do
      res = paymentCheck(length(array)-1, Enum.at(array, rowIndex), rowIndex, users, result)
      arrayPaymentsCheck(array, rowIndex-1, users, res)
    end

  def paymentCheck(-1, _, _, _, result) do result end

  def paymentCheck(colIndex, row, rowIndex, users, result) do
    _result = case Enum.at(row, colIndex) do
      "0" -> result
      _ ->
      if  rowIndex==colIndex do
        result
      else
      from = Enum.at(users, colIndex)
      to = Enum.at(users, rowIndex)
     # res = from <> " - " <> Enum.at(row, colIndex) <> " -> " <> to

      res = {from, Enum.at(row, colIndex) , to}
      [res | result]
      end
    end
    paymentCheck(colIndex-1, row, rowIndex, users, _result)
  end



  def createArray(conn) do
    users = getUsers(conn)
    users = if length(users) < 3 do
        ["temp" | users]
      else
      users
    end

    bills = getBills(conn)

    indexes = length(users)

    row = List.duplicate(0, indexes)
    array = List.duplicate(row, indexes)
    result= calcArrayBills(length(bills)-1, bills,users,array)

    list_string = inspect(result)

    list_string = String.replace(list_string, "], [", ";")
    list_string = String.replace(list_string, "]]", "")
    list_string = String.replace(list_string, "[[", "")
    list_string = String.replace(list_string, " ", "")
    list_string
  end


  def create(conn, %{"bill" => bill_params}) do

    title = bill_params["title"]
    price = bill_params["price"]
    payer = bill_params["payer"]
    users = getUsers(conn)

    checkboxes = Enum.map(users, fn user ->Map.get(bill_params, "checkbox_#{user}") end)

    usersToSplit = Enum.zip(users, checkboxes)

    anySelected = Enum.any?(usersToSplit, fn user ->  elem(user,1) ==  "true" end)

    usersToSplit = case anySelected do
      false ->
        index = Enum.find_index(usersToSplit, fn user ->  elem(user,0) == payer end)
        List.replace_at(usersToSplit, index, {payer ,"true"})
        _-> usersToSplit
    end

    bills = getBills(conn)

    id= case bills do
      nil ->0;
      _-> case length(bills) do
      nil-> 0;
      0->0;
      _->
        Enum.at((Enum.at(bills, length(bills)-1)), 3)+1
    end
    end

    new_bill = [title, price,  usersToSplit,  id, payer]

    newList = case bills do
      nil->[new_bill];
      _->bills ++ [new_bill]
    end

    binary = :erlang.term_to_binary(newList)
    conn = put_session(conn, "bills", binary)

    Phoenix.Controller.redirect(conn, to: "/")
  end

end

splitter/lib/splitter_web/views/bills_view.ex
defmodule SplitterWeb.BillsView do
  use SplitterWeb, :view

end

splitter/lib/splitter_web/templates/bills/index.html.eex
<%= if flash = get_flash(@conn, :alert) do %>
<div class="alert" style="color:red; font-weight: 600; text-align:center"><%= flash %></div>
<hr>
<% end %>



<%= if @bills do %>
<%= if flash = get_flash(@conn, :splitResult) do %>
<div style="text-align:center">
<%= for fl <- get_flash(@conn, :splitResult) do %>
<div>  <div  class="text-frame" > <%= elem(fl,0) %></div> <div class="blockHead"><span class="blocktext"><%= elem(fl,1) %> </span></div><div  class="text-frame" ><%= elem(fl,2) %> </div></div>
<% end %>
</div>
<hr>
<% else %>
<%= if length(@users)>1 do %>
<div style="text-align:center">
<%= link to: Routes.bills_path(@conn, :splitBills), method: :get, class: "btn btn-primary" do %>
<button type="button">Oblicz
</button>
    <% end %>
</div>

<hr>

<% end %>



<% end %>
<% end %>
<%= if @users do %>
<%= form_for @changeset, Routes.bills_path(@conn, :create), fn f -> %>

<label>
    Nowy rachunek:
    <div style="font-size: x-small;">Nazwa rachunku:</div> <%= text_input f, :title, placeholder: 'Nazwa rachunku' %>
    <div style=" font-size: x-small;">Osoby do podziału:</div>
    <%= for user <- @users do %>
    <%= if user do %>
    <%= checkbox f, :"checkbox_#{user}", value: user,  id: "checkbox-#{user}", checked: "checked"  %> <%= user %>
    <% end %>
    <% end %>
    <div style="font-size: x-small;">Kwota:</div>
    <%= number_input f, :price, placeholder: 'Kwota', step: '0.01', required: "required" %>
    <div style="font-size: x-small;">Opłacający:</div>
    <%= select f, :payer, @users %>
</label>
<%= submit "Dodaj" %>
<% end %>
<hr>

<h1>Osoby</h1>
<% end %>

<div class="row">

    <%= if @users do %>
    <div class="column">
    <%= for user <- @users do %>
    <%= if user do %>
    <div class="row">
    <div class="column">
        <h2><%= user %></h2>
    </div>

    <div class="column">
        <%= link to: Routes.bills_path(@conn , :trashUser_button, user), method: "DELETE", class: "btn btn-primary" do %>
        <button type="button" class="trash-btn" ><%= Bootstrap.Icons.trash_fill() %>

        </button>
        <% end %>
    </div>
    </div>
    <% end %>
    <% end %>
    </div>
    <% end %>

    <div class="column">
        <%= form_for @changeset, Routes.bills_path(@conn, :createUser), fn f -> %>

        <label>
            Nowa osoba: <%= text_input f, :user, placeholder: 'Nazwa' %>
        </label>

        <%= submit "Dodaj" %>
         <% end %>
    </div>

</div>

<hr>

<%= if @users do %>


<%= if @bills do %>
<h1>Rachunki</h1>
<%= for bill <- @bills do %>
<%= if bill do %>
<div class="row">
    <div class="column">

    <h2><%= Enum.at(bill,0) %>
    </h2> <div style="font-weight: 400;"> Kwota: <div  class="text-frame"><%= Enum.at(bill,1) %>   </div></div>
        <div style="color:red; font-weight: 400;">   Osoby do podziału:
        <%= for user <- Enum.at(bill,2) do %>
        <%= if(elem(user, 1) == "true") do %>
            <div  class="text-frame" >
                <%=  elem(user, 0)%>
            </div>
            <%  else %>
             <% '' %>
            <% end %>
         <% end %>
    </div>
        <div style="color:blue; font-weight: 400;"> Opłacający:  <div  class="text-frame" ><%= Enum.at(bill,4)  %>   </div></div>
        <div style="color:green; font-weight: 400;"> ID: <%= Enum.at(bill,3)  %></div>

    </div>
    <div class="column" style="width:10%">
        <%= link to: Routes.bills_path(@conn, :trash_button, Enum.at(bill,3)), method: "DELETE", class: "btn btn-primary" do %>
        <button type="button" class="trash-btn" ><%= Bootstrap.Icons.trash_fill() %>

        </button>
        <% end %>

    </div>

</div>
<hr>
<% end %>
<% end %>
<% end %>


<% end %>